FROM golang:alpine3.20 AS builder
RUN mkdir /app
WORKDIR /app
COPY . .
RUN go mod tidy

RUN GOOS=linux GOARCH=amd64 go build -o ./word-of-wisdom-client
 
FROM alpine:3.20.0
WORKDIR /
COPY --from=builder /app/word-of-wisdom-client .

ENV POW_CLIENT_URL="http://localhost:12000/words"

CMD ["/word-of-wisdom-client", "client", "--endless"]